<?php 

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

function news_view_alter_theme($existing, $type, $theme, $path) {
  return array('news_view_alter' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'data' => array(),
                'baseurl' => array(),
                'count' => null,
            ),
        )
    );
}



// function news_view_alter_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
   
//     if ($view->id() == 'news' && $view->getDisplay()->display['id'] == 'page_2'){
//    //  $url_date = arg(1);
//    //   $archive_month = substr($url_date, 0, 2);
//    //   $archive_year = substr($url_date, 2);
//    //   $str_compare = $archive_year . "-" . $archive_month;
//    //   // print('<pre style="color:red;">');
//    //   // print_r($str_compare);
//    //   // print('</pre>');
//    //   // exit;
//       $request = \Drupal::request();
//       $current_path = $request->getPathInfo();
//       $path_args = explode('/', $current_path);
//       $url_date = $path_args[2];
//       $archive_month = substr($url_date, 0, 2);
//       $archive_year = substr($url_date, 2,4);
//       $archive_day = substr($url_date, 6);
//       $str_compare = $archive_year . "-" . $archive_month ."-" . $archive_day;
//       $query->where[1]['conditions']['2']['value'][':node__field_news_date.field_news_date_value'] = $str_compare;
//       $query->where[1]['conditions']['2']['value'][':node__field_news_date.field_news_date_value1'] = $str_compare;
//       print('<pre style="color:red;">');
//       print_r($query->where[1]['conditions']['2']);
//       print('</pre>');
//       exit;
//     }
// }